# Critical default settings:
# disable_system_gems
# disable_rubygems
#bundle_path ".gems/bundler_gems"

source 'https://rubygems.org'
# List gems to bundle here:
# gem 'appengine-rack'
# gem 'appengine-apis'
gem "dm-appengine"
# gem "will_paginate"
# gem 'jruby-rack', '0.9.7'
# gem 'rack', '0.9.1'
gem "sinatra"
# gem 'rails', '2.3.5'
# gem 'builder'
# gem 'padrino', '0.2.9'
# gem 'activesupport', '2.3.3'
# gem 'rake'
# gem 'i18n'
# gem 'warden'
# gem 'actionmailer', '2.3.3'
